//This file is auto generated by CSVDataEditor. All edit will be overrided when re-generating
#if UNITY_EDITOR
using CsvHelper.Configuration;
using UnityEngine;
#endif
using System;
using System.Collections.Generic;

public class StringLz: ConfigBase<StringLzStructure>
{
    public List<StringLzStructure> Data = new List<StringLzStructure>();

    protected override List<StringLzStructure> GetData()
    {
        return this.Data;
    }
}

[Serializable]
public class StringLzStructure: Localizable
{
    [SerializeField] private string m_Key;
    public string Key
    {
        get => m_Key;
        private set
        {
            m_Key = value;
        }
    }

}

#if UNITY_EDITOR
public class StringLzStructureMap : ClassMap<StringLzStructure>
{
    public StringLzStructureMap()
    {
        Map(m => m.Key).Name("KEY");
        Map(m => m.vi).Name("VI");
        Map(m => m.en).Name("EN");
    }
}
#endif