//This file is auto generated by CSVDataEditor. All edit will be overrided when re-generating
using CsvHelper;
using System;
using UnityEditor;
using UnityEngine;

public static partial class CSVDataEditor
{
    private static void CSV2SO(CsvReader csv, string fileName)
    {
        switch (fileName)
        {
            case "StringLz":
                csv.Context.RegisterClassMap<StringLzStructureMap>();
                StringLz cfg_StringLz = ScriptableObject.CreateInstance<StringLz>(); ;
                SkipHeader(csv);
                while (csv.Read())
                {
                    cfg_StringLz.Data.Add(csv.GetRecord<StringLzStructure>());
                }
                AssetDatabase.CreateAsset(cfg_StringLz, AssetConst.CreatPath(new string[] { _ingameConfigPath, $"StringLz.asset" }));
                break;
        }
    }
}
